[package]
name = "no_bs_fcs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5.0"
thiserror = "1.0.58"
polars = { version = "0.39.2", features = ["lazy"]}